### PR TITLE
Add Bardagh's ship variants

### PR DESCRIPTION
**Pull request by Bardagh**
Adding my ship variants plugin to the list.

### CODE REVIEW

**Review by MCOfficer — CHANGES_REQUESTED** [review]
The change in this repository is fine, however your repository contains the plugin within an additional folder (`Bardagh's Ship Variants 1.1.1 `). Plugin repositories are required to *be* the plugin, e.g. contain the `data`, `images` etc. folder/files at the top level.

**Comment by Bardagh** [comment]
> 
> 
> The change in this repository is fine, however your repository contains the plugin within an additional folder (`Bardagh's Ship Variants 1.1.1 `). Plugin repositories are required to _be_ the plugin, e.g. contain the `data`, `images` etc. folder/files at the top level.

Oops. Easily fixed, though.

I hope this catches on. Unfortunately you end up with a lot more ships in the map shipyard view, but the only fix I see for that short of changing the core executable is invisible missions to make you forget ship variants, if that's even possible.

**Review by MCOfficer — CHANGES_REQUESTED** [review]
Didn't see this earlier, but `version` needs to point to a valid git ref, f.e. a tag or commit.

**Comment by Bardagh** [comment]
Are there still conflicts? I updated it with the requested changes. If I missed something please lmk.

**Comment by MCOfficer** [comment]
Yes, the `version` needs to be a git tag. You only have the tags `1.0` and `1.1.1` in your repository, not `1.1`.

As a rule of thumb: If `YOUR_REPO_URL/archive/VERSION.zip` doesn't work, it's no good. With 1.1, that'd be <https://github.com/Bardagh/ship-variants/archive/1.1.zip>

**Comment by Bardagh** [comment]
> 
> 
> Yes, the `version` needs to be an existing git tag or commit. You only have the tags `1.0` and `1.1.1` in your repository, not `1.1`.
> 
> As a rule of thumb: If `YOUR_REPO_URL/archive/VERSION.zip` doesn't work, it's no good. With 1.1, that'd be `https://github.com/Bardagh/ship-variants/archive/1.1.zip`.

Oops. I think it's fixed now. Thank you for walking me through this.

**Comment by Bardagh** [comment]
I feel special. Thanks again ^_^

**Pull request merged**
